services:
  - type: web
    name: django-nelson-dev
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn project.wsgi:application"
    runtime: python
    region: oregon  # ou frankfurt selon ta localisation
    plan: free
    branch: main  # ou master si tu utilises encore "master"
    autoDeploy: true

    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: EMAIL_HOST_USER
        value: "info@nelson-dev.com"
      - key: EMAIL_HOST_PASSWORD
        sync: false  # Tu la rentreras manuellement dans le dashboard Render
      - key: DATABASE_URL
        fromDatabase:
          name: nelson-postgres
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings_render

databases:
  - name: nelson-postgres
    plan: free
    region: oregon  # ou frankfurt
